services:
  app:
    container_name: app-test
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      STORAGE_PATH: "/app/uploads"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/test"
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - app-storage:/app/uploads
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

  db:
    image: postgres:17.2
    container_name: db-test
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - app-pg-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres123"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"

volumes:
  app-pg-data:
  app-storage: